name: Windows - LiteManager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 60 # Reduced timeout, change if necessary

    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          Start-Process -FilePath "Downloads.bat" -Wait # Using Start-Process for better execution control

      - name: Connect to LiteManager
        run: |
          Start-Process -FilePath "show.bat" -Wait # Ensuring processes are finished before continuing

      - name: Time Counter
        run: |
          Start-Process -FilePath "loop.bat" -Wait # Managing process better with Start-Process
